<expr>      ::= <indefdate> 
             | <defdate>

<indefdate> ::= <month> <daynum> 
            | <namedindefdate>
            | <optdet> <ord> "day" "of" <month>
            | <day>
            | <day> + <daynum>

<date>      ::= <indefdate>
            | <indefdate> <year>
            | <dayspec> <month> 
            | "next" <indefdate>
            | "last" <indefdate>
            | "this" <indefdate>
            | <int> <delta> "before" <date> 
            | <int>< <delta> "after" <date>
            | <nameddate>
            | <optdet> <ord> "day" "of" <year>
            | <optdet> <ord> "day" "of" <optdet> <ord> "week" "of" <year>

<year>      ::= <int> 
            | <int> <era>

<era>       ::= "bc"
            | "ad"
            | "bce" 
            | "ce"

<month>     ::= "january"
            | "february"
            | "march"
            | "april"
            | "may"
            | "june"
            | "july"
            | "august"
            | "september" 
            | "october"
            | "november"
            | "december"

<day>       ::= "monday"
            | "tuesday"
            | "wednesday"
            | "thursday"
            | "friday"
            | "saturday"
            | "sunday"

<ord>       ::= <int>"st"
            | <int>"nd"
            | <int>"rd"
            | <int>"th"

<optdet>    ::= "the"
            | ""
