<expr>      := <indefdate> 
             | <defdate>

<indefdate> := <month> <daynum> 
            | <namedindefdate>
            | <ord> day of <month>
            | <day>
            | <day> + <daynum>

<date>      := <indefdate>
            | <indefdate> <year>
            | <dayspec> <month> 
            | next <indefdate>
            | last <indefdate>
            | this <indefdate>
            | <int> <delta> before <date> 
            | <int>< <delta> after <date>
            | <nameddate>
            | <ord> day of <year>
            | <ord> day of <ord> week of <year>

<year>      := <int> 
            | <int> <era>

<era>       := bc
            | ad
            | bce 
            | ce

<month>     := january
            | february
            | march
            | april
            | may
            | june
            | july
            | august
            | september 
            | october
            | november
            | december

<day>       := monday
            | tuesday
            | wednesday
            | thursday
            | friday
            | saturday
            | sunday

<ord>       := <int>st 
            | <int>nd
            | <int>rd
            | <int>th
