const keywords = {
    day: { $type: "ivlspc", $val: "day" },
    days: { $type: "ivlspc", $val: "days" },
    before: { $type: "dir", $val: "before" },
    after: { $type: "dir", $val: "after" },
    boxing: { day: { $type: "dayconst", $val: "boxing day" }},
    groundhog: { day: { $type: "dayconst", $val: "groundhog day" }},
    christmas: { eve: { $type: "dayconst", $val: "christmas eve" }},
    'new': { "year's": { eve: { $type: "dayconst", $val: "new year's eve" }}},
    ad: { $type: "yearlbl", $val: "ad" },
    bc: { $type: "yearlbl", $val: "bc" }, 
    ce: { $type: "yearlbl", $val: "ce" },
    bce: { $type: "yearlbl", $val: "bce" },
    january: { $type: "month", $val: "january" },
    february: { $type: "month", $val: "february" },
    march: { $type: "month", $val: "march" },
    april: { $type: "month", $val: "april" },
    may: { $type: "month", $val: "may" },
    june: { $type: "month", $val: "june" },
    july: { $type: "month", $val: "july" },
    august: { $type: "month", $val: "august" },
    september: { $type: "month", $val: "september" },
    october: { $type: "month", $val: "october" },
    november: { $type: "month", $val: "november" },
    december: { $type: "month", $val: "december" },
    jan: { $type: "month", $val: "january" },
    feb: { $type: "month", $val: "february" },
    mar: { $type: "month", $val: "march" },
    apr: { $type: "month", $val: "april" },
    may: { $type: "month", $val: "may" },
    jun: { $type: "month", $val: "june" },
    jul: { $type: "month", $val: "july" },
    aug: { $type: "month", $val: "august" },
    sep: { $type: "month", $val: "september" },
    oct: { $type: "month", $val: "october" },
    nov: { $type: "month", $val: "november" },
    dec: { $type: "month", $val: "december" },
    one: { $type: "int", $val: 1}, 
    two: { $type: "int", $val: 2}, 
    three: { $type: "int", $val: 3}, 
    four: { $type: "int", $val: 4}, 
    five: { $type: "int", $val: 5}, 
    six: { $type: "int", $val: 6}, 
    seven: { $type: "int", $val: 7}, 
    eight: { $type: "int", $val: 8}, 
    nine: { $type: "int", $val: 9}, 
    ten: { $type: "int", $val: 10}, 
    eleven: { $type: "int", $val: 11}, 
    twelve: { $type: "int", $val: 12}, 
    thirteen: { $type: "int", $val: 13}, 
    fourteen: { $type: "int", $val: 14}, 
    fifteen: { $type: "int", $val: 15}, 
    sixteen: { $type: "int", $val: 16}, 
    seventeen: { $type: "int", $val: 17}, 
    eighteen: { $type: "int", $val: 18}, 
    nineteen: { $type: "int", $val: 19}, 
    twenty: { $type: "int", $val: 20}
}

function generateKeywords() {
    return keywords;
}

module.exports = generateKeywords;
