const keywords = {
    'next': { $val: 'next' },
    'last': { $val: 'last' },
    'this': { $val: 'this' },
    'day': { $val: 'day' },
    'days': { $val: 'days' },
    'before': { $val: 'before' },
    'after': { $val: 'after' },
    'of': { $val: 'of' },
    'battle': { 'of': { 'hastings': { $val: 'battle of hastings', $type: 'nameddate' }}},
    'd-day': { $val: 'd-day', $type: 'nameddate' },
    'halloween': { $val: 'halloween', $type: 'namedindefdate' },
    'boxing': { 'day': { $val: 'boxing day', $type: 'namedindefdate' } },
    'groundhog': { 'day': { $val: 'groundhog day', $type: 'namedindefdate' } },
    'christmas': { 'eve': { $val: 'christmas eve', $type: 'namedindefdate' } },
    'new': { 'year\'s': { 'eve': { $val: 'new year\'s eve', $type: 'namedindefdate' } } },
    'ad': { $val: 'ad', $type: 'era'},
    'bc': { $val: 'bc', $type: 'era'}, 
    'ce': { $val: 'ce', $type: 'era'},
    'bce': { $val: 'bce', $type: 'era'},
    'january': { $val: 'january', $type: 'month' },
    'february': { $val: 'february', $type: 'month' },
    'march': { $val: 'march', $type: 'month' },
    'april': { $val: 'april', $type: 'month' },
    'may': { $val: 'may', $type: 'month' },
    'june': { $val: 'june', $type: 'month' },
    'july': { $val: 'july', $type: 'month' },
    'august': { $val: 'august', $type: 'month' },
    'september': { $val: 'september', $type: 'month' },
    'october': { $val: 'october', $type: 'month' },
    'november': { $val: 'november', $type: 'month' },
    'december': { $val: 'december', $type: 'month' },
    'jan': { $val: 'january', $type: 'month' },
    'feb': { $val: 'february', $type: 'month' },
    'mar': { $val: 'march', $type: 'month' },
    'apr': { $val: 'april', $type: 'month' },
    'may': { $val: 'may', $type: 'month' },
    'jun': { $val: 'june', $type: 'month' },
    'jul': { $val: 'july', $type: 'month' },
    'aug': { $val: 'august', $type: 'month' },
    'sep': { $val: 'september', $type: 'month' },
    'oct': { $val: 'october', $type: 'month' },
    'nov': { $val: 'november', $type: 'month' },
    'dec': { $val: 'december', $type: 'month' },
    'one': { $val: 1, $type: 'int' }, 
    'two': { $val: 2, $type: 'int' }, 
    'three': { $val: 3, $type: 'int' }, 
    'four': { $val: 4, $type: 'int' }, 
    'five': { $val: 5, $type: 'int' }, 
    'six': { $val: 6, $type: 'int' }, 
    'seven': { $val: 7, $type: 'int' }, 
    'eight': { $val: 8, $type: 'int' }, 
    'nine': { $val: 9, $type: 'int' }, 
    'ten': { $val: 10, $type: 'int' }, 
    'eleven': { $val: 11, $type: 'int' }, 
    'twelve': { $val: 12, $type: 'int' }, 
    'thirteen': { $val: 13, $type: 'int' }, 
    'fourteen': { $val: 14, $type: 'int' }, 
    'fifteen': { $val: 15, $type: 'int' }, 
    'sixteen': { $val: 16, $type: 'int' }, 
    'seventeen': { $val: 17, $type: 'int' }, 
    'eighteen': { $val: 18, $type: 'int' }, 
    'nineteen': { $val: 19, $type: 'int' }, 
    'first': { $val: 1, $type: 'ord' }, 
    'second': { $val: 2, $type: 'ord' }, 
    'third': { $val: 3, $type: 'ord' }, 
    'fourth': { $val: 4, $type: 'ord' }, 
    'fifth': { $val: 5, $type: 'ord' }, 
    'sixth': { $val: 6, $type: 'ord' }, 
    'seventh': { $val: 7, $type: 'ord' }, 
    'eighth': { $val: 8, $type: 'ord' }, 
    'ninth': { $val: 9, $type: 'ord' }, 
    'tenth': { $val: 10, $type: 'ord' }, 
    'eleventh': { $val: 11, $type: 'ord' }, 
    'twelveth': { $val: 12, $type: 'ord' }, 
    'thirteenth': { $val: 13, $type: 'ord' }, 
    'fourteenth': { $val: 14, $type: 'ord' }, 
    'fifteenth': { $val: 15, $type: 'ord' }, 
    'sixteenth': { $val: 16, $type: 'ord' }, 
    'seventeenth': { $val: 17, $type: 'ord' }, 
    'eighteenth': { $val: 18, $type: 'ord' }, 
    'nineteenth': { $val: 19, $type: 'ord' }, 
    'twenty': { $val: 20, $type: 'int' },
    'monday': { $val: 'monday' },
    'tuesday': { $val: 'tuesday' },
    'wednesday': { $val: 'wednesday' },
    'thursday': { $val: 'thursday' },
    'friday': { $val: 'friday' },
    'saturday': { $val: 'saturday'},
    'sunday': { $val: 'sunday'},
    'the': { $val: 'the' }
}

function generateKeywords() {
    return keywords;
}

module.exports = generateKeywords;
