const keywords = {
    'next': { $val: 'next' },
    'last': { $val: 'last' },
    'this': { $val: 'this' },
    'day': { $val: 'day' },
    'days': { $val: 'days' },
    'before': { $val: 'before' },
    'after': { $val: 'after' },
    'of': { $val: 'of' },
    'halloween': { $val: 'halloween' },
    'boxing': { 'day': { $val: 'boxing day' } },
    'groundhog': { 'day': { $val: 'groundhog day' } },
    'christmas': { 'eve': { $val: 'christmas eve' } },
    'new': { 'year\'s': { 'eve': { $val: 'new year\'s eve' } } },
    'ad': { $val: 'ad' },
    'bc': { $val: 'bc' }, 
    'ce': { $val: 'ce' },
    'bce': { $val: 'bce' },
    'january': { $val: 'january' },
    'february': { $val: 'february' },
    'march': { $val: 'march' },
    'april': { $val: 'april' },
    'may': { $val: 'may' },
    'june': { $val: 'june' },
    'july': { $val: 'july' },
    'august': { $val: 'august' },
    'september': { $val: 'september' },
    'october': { $val: 'october' },
    'november': { $val: 'november' },
    'december': { $val: 'december' },
    'jan': { $val: 'january' },
    'feb': { $val: 'february' },
    'mar': { $val: 'march' },
    'apr': { $val: 'april' },
    'may': { $val: 'may' },
    'jun': { $val: 'june' },
    'jul': { $val: 'july' },
    'aug': { $val: 'august' },
    'sep': { $val: 'september' },
    'oct': { $val: 'october' },
    'nov': { $val: 'november' },
    'dec': { $val: 'december' },
    'one': { $val: 1 }, 
    'two': { $val: 2 }, 
    'three': { $val: 3 }, 
    'four': { $val: 4 }, 
    'five': { $val: 5 }, 
    'six': { $val: 6 }, 
    'seven': { $val: 7 }, 
    'eight': { $val: 8 }, 
    'nine': { $val: 9 }, 
    'ten': { $val: 10 }, 
    'eleven': { $val: 11 }, 
    'twelve': { $val: 12 }, 
    'thirteen': { $val: 13 }, 
    'fourteen': { $val: 14 }, 
    'fifteen': { $val: 15 }, 
    'sixteen': { $val: 16 }, 
    'seventeen': { $val: 17 }, 
    'eighteen': { $val: 18 }, 
    'nineteen': { $val: 19 }, 
    'twenty': { $val: 20 },
    'monday': { $val: 'monday' },
    'tuesday': { $val: 'tuesday' },
    'wednesday': { $val: 'wednesday' },
    'thursday': { $val: 'thursday' },
    'friday': { $val: 'friday' },
    'saturday': { $val: 'saturday'},
    'sunday': { $val: 'sunday'},
    'the': { $val: 'the' }
}

function generateKeywords() {
    return keywords;
}

module.exports = generateKeywords;
